[[
	socket的文档wiki地址：http://console.oa.com:9003/wiki/index?id=client###
	未完成的工作：
	1、日志
		链路日志跟踪
		收发包响应时间、异常包、发送失败的包
		上报方案：内容分级、上报方式、上报异常解决方案
	2、配置刷新
		socket连接后主动推送配置更新，通过配置判断是否强制重连
	3、安全校验
		ssid上报access记录
		go每隔5分钟主动推送
		客户端记录每次获得ssid的时间，发包时ssid超过5分钟未刷新时，主动请求同步，并且上报access
		重连：客户端上报ssid、mid到access
]]