
·"
MsgType.protoXGMsg*Õ
GameServerId
CLI_CMD_LOGINÅ 
CLI_CMD_RETURNÇ 
CLI_CMD_SITDOWNÉ 
CLI_CMD_STANDÖ 
CLI_CMD_REQ_BETÑ 
CLI_CMD_REQ_AUTOSITÜ 
CLI_CMD_REQ_CANCEL_AUTOSITá 
CLI_CMD_REQ_SEND_MSGà 
CLI_CMD_REQ_SEND_EMOTIONâ 
CLI_CMD_REQ_SHOW_HAND_CARDä 
CLI_CMD_REQ_SEND_CHIPSå 
CLI_CMD_SEND_GIFTã 
CLI_CMD_SEND_HDç 
CLI_CMD_CHANGE_GIFTé 
CLI_CMD_ADD_FRIENDè 
CLI_CMD_HEART_BEATê 
CLI_CMD_NEXT_STANDë 
CLI_CMD_BACK_SEATí 
CLI_CMD_SEND_DEALER_MONEYî 
CLI_CMD_BUY_NEXT_LOTTO† 
CLI_CMD_AUTO_BUY_LOTTO° "
CLI_CMD_CANCEL_AUTO_BUY_LOTTO¢ !
CLI_CMD_DELAY_AUTO_BUY_LOTTO£ 
CLI_CMD_REQ_SEND_MSG_NEW§ 
SVR_CMD_LOGIN_SUCCÅ@
SVR_CMD_LOGIN_FAILÇ@
SVR_CMD_RELOGIN_SUCCè@
SVR_CMD_SITEDOWN_FAILÑ@
SVR_CMD_USER_CRASHì@
SVR_CMD_SEND_CHIPS_FAILò@
SVR_CMD_EXTRA_LOGIN_INFO¢@"
SVR_CMD_SEND_DEALER_CHIP_SUCCß@"
SVR_CMD_SEND_DEALER_CHIP_FAIL®@
SVR_CMD_CONNECTGAMESERVERáB
SVR_CMD_CHANGE_PLAYER_GIFTàB
SVR_BCCMD_SEND_GIFTï@
SVR_BCCMD_SEND_CHIPSñ@
SVR_BCCMD_BET_SUCCà@
SVR_BCCMD_BET_TURN_TOå@
SVR_BCCMD_STANDÜ@
SVR_BCCMD_GAME_STARTá@
SVR_BCCMD_SITDOWNÖ@
SVR_BCCMD_CARD_FLOPâ@
SVR_BCCMD_CARD_TRUNä@
SVR_BCCMD_CARD_RIVERã@
SVR_BCCMD_CHIPSPOTSç@
SVR_BCCMD_GAME_OVERé@
SVR_BCCMD_CHATMSGë@
SVR_BCCMD_EMOTIONí@
SVR_BCCMD_SHOW_HAND_CARDî@
SVR_BCCMD_ALLINÅ`
SVR_BCCMD_SEND_HDó@
SVR_BCCMD_KITOUTô@
SVR_BCCMD_ADD_FRIENDö@
SVR_BCCMD_LEAVE_SEATõ@
SVR_BCCMD_SVR_SWITCHÄB
SVR_BCCMD_SVR_STOPÅB 
SVR_BCCMD_BUY_LOTTO_SUCCEED¡@
SVR_BCCMD_BUY_LOTTO_FAIL¬@
SVR_BCCMD_CHATMSG_NEW—@
SERVER_COMMAND_ANT_OVERÇB
SERVER_COMMAND_EXP_LIMITÑB
SVR_BCCMD_TABLE_OWNER£@%
 SERVER_CMD_BROADCAST_OWNER_LEAVE§@
SERVER_CMD_LOGOUT¶@
SERVER_CMD_LOGOUT_SUCCESS©@'
"SERVER_CMD_RPRIVATE_LOGOUT_SUCCESS∞@
SVR_BCCMD_BLIND_CHANGE_TÅ‡
SVR_BCCMD_MATCH_END_TÉ‡
SVR_BCCMD_ALL_RANKING_TÑ‡
SVR_BCCMD_TABLE_ID_TÜ‡!
SVR_BCCMD_COUNT_DOWN_TIME_Tâ‡
SVR_BCCMD_SWITCH_TABLE_Tä‡#
SVR_BCCMD_SWITCH_TABLE_SUCC_Tã‡
SVR_BCCMD_MATCH_START_Tå‡
SVR_BCCMD_MATCH_CLOSE_Tç‡
SVR_BCCMD_MATCH_TIME_Té‡
SVR_CMD_USER_RANKING_Tá‡
SVR_CMD_USER_OUT_TÖ‡
SVR_BCCMD_TABLE_ID_KÉ‚
SVR_BCCMD_MATCH_START_KÅ‚
SVR_BCCMD_MATCH_END_KÇ‚
SVR_BCCMD_BLIND_CHANGE_KÜ‚
SVR_BCCMD_ALL_RANKING_Ká‚
SVR_BCCMD_MATCH_CLOSE_Kà‚
SVR_CMD_USER_RANKING_KÑ‚
SVR_CMD_USER_OUT_KÖ‚
SVR_CMD_MATCH_INFO_Kâ‚*§	

LBServerId
LB_SVR_CMD_SYSTEMÇ 
LB_SVR_CMD_SINGLEÉ 
LB_SVR_CMD_HEARTBEATÅ@
LB_SVR_TYPE_LEVEL_UPÅ 
LB_SVR_TYPE_EXPÑ 
LB_SVR_TYPE_LOTTERYÖ 
LB_SVR_TYPE_MESSAGEÜ 
LB_SVR_TYPE_EDIT_CHIPá 
LB_SVR_TYPE_MATCH_PROMPTà 
LB_SVR_TYPE_INVITE_PLAYâ 
LB_SVR_TYPE_GET_VIPä 
LB_SVR_TYPE_EDIT_SCOREã 
LB_SVR_TYPE_DELAY_PAYå 
LB_SVR_TYPE_SUCCESS_PAYç 
LB_SVR_TYPE_SUCCESS_ACTï 
LB_SVR_TYPE_HEAD_TIPÇ@
LB_SVR_TYPE_SLOTÉ@
LB_SVR_TYPE_ROOM_TIPÑ@
LB_SVR_TYPE_SMALL_LABAÖ@
LB_SVR_TYPE_BIG_LABAÜ@
LB_SVR_TYPE_LOTTO_REWARDá@
LB_SVR_TYPE_LOTTO_POOLà@
LB_SVR_TYPE_SLOT_REWARDä@
LB_SVR_TYPE_PASSDAYã`
LB_SVR_TYPE_UPDATE_GIFTå`
LB_SVR_TYPE_UPDATE_TICKETSó 
LB_SVR_TYPE_PUSH_MESSAGEã@
LB_SVR_TYPE_DOUBLE_LOGINÅ†
LB_SVR_TYPE_PLAYER_NUMÅ`#
LB_SVR_TYPE_DOSH_BOARD_MESSAGEì 
LB_SVR_TYPE_MB_DISCOUNTÅÄ
LB_SVR_TYPE_MB_SYS_MSGÇÄ"
LB_SVR_TYPE_MB_ITEM_DISCOUNTÉÄ
LB_SVR_TYPE_MB_USER_PAYÑÄ(
"LB_SVR_TYPE_MB_DOLL_ACQUIRE_PROMPTÅÄ#
LB_SVR_TYPE_MB_SINGLE_MESSAGEÇÄ%
LB_SVR_TYPE_MB_ACCEPT_RED_PACKSÉÄ*
$LB_SVR_TYPE_MB_COMMON_MESSAGE_PROMPTÑÄ#
LB_SVR_TYPE_PUSH_MATCH_MESSAGEä`*Õ
SlotServerId
SLOT_SVR_SEND_CMD_LOGINÅ !
SLOT_SVR_SEND_CMD_CALCULATORÇ 
SLOT_SVR_SEND_CMD_SLOTÉ !
SLOT_SVR_RECV_CMD_CALCULATORÅ@ 
SLOT_SVR_RECV_CMD_SLOT_SUCCÇ@ 
SLOT_SVR_RECV_CMD_SLOT_FAILÅ`
CLI_CMD_PROXY_LOGINÅ¿
CLIENT_CMD_REQ_REBUYÅ&
CLIENT_CMD_REQ_ADDONÇ&
SERVER_CMD_USER_REBUYë‡ 
SERVER_CMD_BROADCAST_REBUYê‡'
!SERVER_CMD_BROADCAST_REBUY_SUCESSì‡(
"SERVER_CMD_BROADCAST_ALL_REBUY_ENDí‡%
SERVER_CMD_USER_PRIZE_RANK_INFOï‡
SERVER_CMD_USER_ADDONñ‡,
&SERVER_CMD_BROADCAST_USER_ADDON_SUCESSî‡&
!SERVER_CMD_USER_ADDON_REBUY_FAILDÅF 
SERVER_CMD_MATCH_NOT_STARTó‡
SERVER_CMD_SEND_MIDò‡ 
SERVER_CMD_APPLY_REWARD_NUMÉ&
SERVER_CMD_TRACE_FRIEND≤@BH